### ISSUE TITLE
Finish configuring projects for new rotating logs

### ISSUE THREAD

**Issue by meg-codes** [Princeton-CDH/cdh-ansible#14]
The following work needs to happen to make rotating logs happen on all projects:

-  Configure log rotation on `cdh` and `derridas-margins`
- Place log files in updated location.
-  Add logging roles to `cdh` and `derridas-margins` playbooks

**Comment by thatbudakguy** [comment]
from what I can see on this:
- `mep` and `ppa` have some configuration in `local_settings.py` that is not included in `cdh-web` or `derrida` that seems related to log rotation: https://github.com/Princeton-CDH/CDH_ansible/blob/8b971961a366bf9a24a54bd01417e734e3305665/templates/ppa/local_settings.py#L34-L41
- there is a `configure_logging` role that is not included in in the `cdh-web` playbook, but is included for `derrida`.

so if I'm understanding this right we still need to:
- [ ] copy the above conf block into the `local_settings.py` for `cdh-web`
- [ ] copy the above conf block into the `local_settings.py` for `derrida`
- [ ] add the `configure_logging` role to the `cdh-web` playbook

not sure what "place log files in updated location" entails.
