### ISSUE TITLE
switch staging apps that use solr to the new jammy solr staging server

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/cdh-ansible#190]
new solr url is lib-solr8d-staging.princeton.edu

new solr staging host is  lib-solr-staging4d

CDH users should be on the ssh list

affected applications: ~geniza~, shxco, prosody

(geniza not affected because it is on solr9)

**Comment by rlskoeser** [comment]
@kayiwa do I need a new zookeeper host string as well? Trying to deploy and getting an error because my configset doesn't exist.

**Comment by kayiwa** [comment]
Sorry about that. Yes there is. The ensemble is lib-zk-staging{1,2,3}d @rlskoeser
