### ISSUE TITLE
add datadog logs

### ISSUE THREAD

**Issue by kayiwa** [Princeton-CDH/cdh-ansible#199]
### User story

As a CDH person:
- I want to know why my application is getting 500 errors
- I want to get more information and correlated them to the loadbalancers logs from datadog

### Acceptance criteria

- [x] I can log to the datadog web application and filter for my_app and nginx to determine what is going on

### Implementation notes, if any

- [x] find out where application logs are written
- [x] Install configure datadog on production application
- [x] add a new role to ship the logs

**Comment by rlskoeser** [comment]
cdh-ansible has a `configure_logging` role, although we have proposed moving it into the setup role: #165

We have `logging_dir` and `logging_path` directories for application log files, but I don't know if we want application logs or nginx logs or both.

**Comment by rlskoeser** [comment]
I don't know if it's part of this task or a new one, but as a separate update we want to filter out all the datadog status checks (and maybe the load balancer checks as well?).

**Comment by rlskoeser** [comment]
This is working great now, closing the issue.
