### ISSUE TITLE
get Prodigy deploy template running in Ansible Tower

### ISSUE THREAD

**Issue by jerielizabeth** [Princeton-CDH/cdh-ansible#222]
I setup the template in Ansible Tower but it fails because Tower isn't installing an external role we depend on for running supervisord.

Alicia is aware of this problem; hopefully she'll be able to figure out something next week that will resolve it.

**Comment by mnaydan** [comment]
Assess this issue as part of the updates to get Prodigy running multiple recipes. Blocked right now because of a dependency that doesn't get installed (Alicia needs to help!)

**Comment by mnaydan** [comment]
Decided to do local install instead.
