### ISSUE TITLE
Permissions are repeatedly reset during project repo clone

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/cdh-ansible#59]
**Describe the bug**
When deploying apps on PUL infrastructure, the beginning of the `build_project_repo` role takes significantly longer than other tasks, and reports `changed: ` each time it is run. The slow part is this step, where we recursively set permissions on the deploy directory to prevent permissions errors when cloning:
https://github.com/Princeton-CDH/cdh-ansible/blob/9a3839cde80c0d77113c170a1c142a0900f098a5/roles/build_project_repo/tasks/main.yml#L18-L27

this is a large recursive operation, so it could potentially take a long time, but it appears to be running (and changing permissions) _every_ time, which doesn't seem right.

**Expected behavior**
The permissions should be set correctly once, and then ansible should detect that there's no need to make a change and report `skipped: `, making the step quicker.

**Comment by rlskoeser** [comment]
This was resolved at some point and is no longer an issue
