### ISSUE TITLE
Configure custom nginx error page for QA/test/vpn-only sites

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/cdh-ansible#60]
Everyone occasionally forgets to log into access test/vpn sites, and it would be helpful to have a different visual reminder to distinguish those sites from library sites.

- remind to login to vpn if not already on campus / on vpn
- add cdh logo somewhere
- should return a 401 not authorized if access is denied due to IP address

Instructions from Francis:

at the bottom of every config generally is
```
server {
    listen 443 ssl;
    server_name cdh-geniza.princeton.edu;
    ...
    include /etc/nginx/conf.d/templates/prod-maintenance.conf;
}
```

and the contents of prod-maintenance
```
error_page 400 401 402 403 404 405 406 407 408 409 410 411 412 413 414 415 416 417 418 421 422 423 424 425 426 428 429 431 451 500 501 502 503 504 505 506 507 508 510 511 = @maintenance;
location @maintenance {
        root /var/local/www/default;
        try_files $uri /index.html =502;
    }
```

And the html file is the error page displayed.

- [ ] create an template based on PUL's template
- [ ] file a PR in `princeton-ansible` to add the stanza to the nginx conf and upload the template

**Comment by acozine** [comment]
If a staging site has `proxy_intercept_errors` is set to `on`, nginx currently returns a `403 Forbidden` error code when the client is connecting from off-campus and not on the VPN.

**Comment by acozine** [comment]
Related to https://github.com/pulibrary/princeton_ansible/pull/4122.

**Comment by rlskoeser** [comment]
hooray! thank you @acozine
