### ISSUE TITLE
As a developer, I want to manage Django tasks through a single role so that I can simplify existing deploy playbooks.

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/cdh-ansible#63]
**Is your feature request related to a problem? Please describe.**
Currently, functionality related to deploying Django apps is spread across several roles:
- `configure_logging`
- `configure_media`
- `django_collectstatic`
- `django_compressor`
- `django_migrate`
- `install_local_settings`

**Describe the solution you'd like**
Ideally, these could all be tasks that are part of a single Django-specific role, which could have shared defaults and dependencies on other roles. New Django-related tasks (for example, https://github.com/Princeton-CDH/geniza/issues/117) can also become part of this role.

**Additional context**
- Ansible [`django_manage` plugin](https://docs.ansible.com/ansible/latest/collections/community/general/django_manage_module.html#ansible-collections-community-general-django-manage-module), from `community.general`
- existing [`ansible-role-django`](https://github.com/cchurch/ansible-role-django) on github

**Comment by rlskoeser** [comment]
Should there be a python role? Logging seems like possibly not django-specific (although perhaps our implementation is); what about virtualenv creation?

Will you duplicate existing tasks so that old playbooks are left unchanged but playbooks for applications deployed on PUL VMs would start using the new role? 

Are the linked django ansible plugins and roles useful at all or just examples we can refer to?

**Comment by thatbudakguy** [comment]
> Should there be a python role

Yes! I think we can basically directly convert the `create_virtualenv` role to a python role; it's a dependency of this role. Will do the necessary parts of that in this issue, but eventually the python role should probably also handle installing the relevant version of python.

> Will you duplicate existing tasks

Yep.

> Are the linked django ansible plugins and roles useful at all

The linked plugin is quite useful and we actually already use it in another role; the linked role does too. It just allows running arbitrary `manage.py` commands with a bit of extra checks/helpers. The linked role is more of an example; in my investigation it appeared to be far too generic/featureful and would need a lot of configuration for us to use as-is. I'm referring to it in case it has useful conventions.

**Comment by rlskoeser** [comment]
Great, thanks for elaborating. Sounds good.

Looking forward to having this managed and organized better!

**Comment by thatbudakguy** [comment]
- [ ] write molecule `verify.yml`
- [ ] test against cdhweb in QA

**Comment by rlskoeser** [comment]
implemented in PR #73 ; remaining tasks have been split into separate issues
