### ISSUE TITLE
playbook / role to synchronize database and media data from production to qa or dev environment

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/cdh-ansible#65]
**Is your feature request related to a problem? Please describe.**
When we want to test against recent production data, we have to manually download sql dumps and media files, copy them, load them into the database or file system, set permissions, update django/wagtail site in the database.  Because it's error prone and because we tend to be lazy, we don't always do always bother with refreshing data when we probably should.

**Describe the solution you'd like**
A script or playbook I can run that does all of this for me.  For QA at least, but for local dev would be super.

general steps needed:
- backup production db
- sync db backup to staging postgres and restore
- backup production site media (user uploaded content)
- sync media backup to staging and restore
- run django migrations (maybe? or could be out of scope) — needed when staging code differs from production
- update django site in db to match environment
- sync solr?

**Comment by acozine** [comment]
Related to https://github.com/pulibrary/princeton_ansible/issues/1522

**Comment by rlskoeser** [comment]
initial replicate playbook merged into main in #117 ; currently supports cdhweb and geniza, for db and media only (solr still tbd), and only supports prod to qa, no automated replication to dev environments yet
