### ISSUE TITLE
Use shallow clone to check out project repo

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/cdh-ansible#86]
**Is your feature request related to a problem? Please describe.**
The `build_project_repo` role currently does a full git checkout of the project's repository each time. We don't need the full git history on the target machine; only the most recent state is necessary.

**Describe the solution you'd like**
A shallow clone will allow us to get the files from github without their git history. It should be sufficient to pass [`depth:1` to the `git` module](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/git_module.html#parameter-depth) in ansible.

The relevant lines are here:
https://github.com/Princeton-CDH/cdh-ansible/blob/80891c61640368e843233e213dac2c0184605a0f/roles/build_project_repo/tasks/main.yml#L29-L37

**Comment by rlskoeser** [comment]
resolved in PR #87
